name: 🔄 Firebase Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Deploy Firebase Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: "preview-${{ github.head_ref || github.ref_name }}"
          projectId: ai4all-platform-fe2e4
