# .github/workflows/firebase-preview.yml
name: 🔄 Firebase Preview Deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies (functions)
        working-directory: ./functions
        run: npm ci

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy Cloud Functions
        run: |
          firebase deploy \
            --only functions \
            --project ai4all-platform-fe2e4

      - name: Deploy Hosting to preview channel
        run: |
          firebase hosting:channel:deploy staging \
            --project ai4all-platform-fe2e4 \
            --expires 7d
